### ISSUE TITLE
Source Code  

### ISSUE THREAD

**Issue by CSJDeveloper** [z-x-yang/DoraemonGPT#2]
I am eagerly awaiting the source code for this paper so that I can test it myself. 
The claims and contributions presented in the paper are truly astonishing. I wonder how the authors achieved these. 

Marked.

**Comment by z-x-yang** [comment]
I appreciate your interest in our paper. We plan to release the code organized after the NeurIPS deadline.

**Comment by CSJDeveloper** [comment]
> I appreciate your interest in our paper. We plan to release the code organized after the NeurIPS deadline.

Thanks! Waiting for this wonderful work and I hope my subsequent work can derive from it.

**Comment by zhanwenchen** [comment]
+1

**Comment by z-x-yang** [comment]
> +1

Thank you for your attention. Recently, my travel commitments have significantly delayed the progress of open-source. However, we have now organized a version for release, and if all goes well, it should be available in the next few days.
